int main(int argc, char **argv)
{
	return 0;
}

#define MK(x)   void fun ## x(void) { \
	asm volatile(		\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
		"nop\nnop\nnop\nnop\nnop\nnop\nnop\nnop\n"\
	);	\
}

//MK(1)
//MK(2)
//MK(3)
//MK(4)
//MK(5)
//MK(6)
//MK(7)
//MK(8)
//MK(9)
//MK(10)
//MK(11)
//MK(12)
//MK(13)
//MK(14)
//MK(15)
//MK(16)
//MK(17)
//MK(18)
//MK(19)
//MK(20)
//MK(21)
//MK(22)
//MK(23)
